#!/bin/bash
set -e

# Set the URL of your RSS feed
RSS_FEED_URL='https://feeds.megaphone.fm/trashtaste'

# Download the RSS feed and parse it using xmllint
RSS_FEED=$(curl -s "$RSS_FEED_URL" | xmllint --format -)

# Extract the title and URL of each podcast episode
TITLES=$(echo -e "$RSS_FEED" | grep "<title>" | tail -n +3 | sed -e 's/.*<title>//g' -e 's/<\/title>.*//g')
URLS=($(echo "$RSS_FEED" | grep "<enclosure" | sed -e 's/.*url="//g' -e 's/".*//g'))

CHOICE=$(echo -e "${TITLES}\nexit" | rofi -theme /usr/local/share/rofi/themes/trashtaste.rasi -dmenu -i -p "Choose an episode:")

# Open the URL of the chosen episode in the default web browser
if [ $? -eq 0 ]; then
  [ "$CHOICE" == "exit" ] && killall rofi-tt
    INDEX=$(echo -e "${TITLES}" | grep -n "$CHOICE" |cut -d : -f 1)
    URL=${URLS[$INDEX-1]}
    # killall mpv
    pgrep rofi-tt >/dev/null && pkill mpv
    mpv  --save-position-on-quit -no-video "$URL"
    pkill rofi-tt
fi




